### ISSUE TITLE
No stored user

### ISSUE THREAD

**Issue by sonypsx** [ZeroOneStudio/gracenote-cli#2]
Hello,

after struggeling around to build your app under Visual Studio, i got the follwing error:
c:\y>MusicID.exe 'MyClientID' 'MyClientTag' C:\y\lic.txt online C:\y\x.wav
Info: No stored user - this must be the app's first run.

error from: gnsdk_manager_user_register()  [on line 316]
        0x90800001 Invalid argument

How can i avoid this - or get rid of this?
I know it must be much more a problem with GNSDK than with your app - but i count on you that you can solve it ;)

Best regards
Martin

**Comment by SergeyKishenin** [comment]
Hello,

I guess you should pass `'online'` in quotes.

**Comment by sonypsx** [comment]
Hello,

hope you had a decent Sylvester!

thanks for the tip - i did try - but with no success.
Here are my tries:

c:\y>MusicID.exe 'MyClientID' 'MyClientTag' C:\y\lic.txt onlin
e C:\y\x.wav

error from: gnsdk_manager_user_create()  [on line 273]
        0x90800009 User Create: error deserializing user data

error from: gnsdk_manager_user_register()  [on line 316]
        0x90800001 Invalid argument

c:\y>1

c:\y>MusicID.exe 'MyClientID' 'MyClientTag' C:\y\lic.txt 'onli
ne' C:\y\x.wav

Usage:
MusicID.exe clientid clientidtag license [local|online] file

c:\y>1

c:\y>MusicID.exe 'MyClientID' 'MyClientTag' C:\y\lic.txt "onli
ne" C:\y\x.wav

error from: gnsdk_manager_user_create()  [on line 273]
        0x90800009 User Create: error deserializing user data

error from: gnsdk_manager_user_register()  [on line 316]
        0x90800001 Invalid argument

Your App only go further if i do not pass "online" without any quotes - but of course again with the mentioned error. Is it possible that Gracenote did change the format of that User whatever JSON/XML?

Best regards
Martin

**Comment by sonypsx** [comment]
Hello,

meanwhile i asked about my license over at gracenote, and the admins there said -> everthing ok.
I would be really happy if i can use your app!

Best regards
Martin

**Comment by sonypsx** [comment]
Hello,

after playing around, i finally found the solution.
For anyone else who is using this tool under windows:
sample.exe "MyClientID" "MyClientTag" "C:\y\lic.txt" "online" "C:\y\x.wav"

You need to double quote EACH parameter!
Regards
Martin

**Comment by SergeyKishenin** [comment]
Glad to hear! Thanks!
